### ISSUE TITLE
Integration tests fail: Selenium server unable to create new session.

### ISSUE THREAD

**Issue by pipw** [hkhosrav/RiPPLE-Client-side#36]
Integration tests were run `$ npm run e2e` on clean checkout of **master** branch `2017-07-28 15:30`. See attached log for details.

[e2e.error.20170728.txt](https://github.com/hkhosrav/RiPPLE-Client-side/files/1182101/e2e.error.20170728.txt)

**Comment by CaptainAchilles** [comment]
Hey Phil,

I think this might be an chrome version issue (or a missing installation). Chrome has recently been improving its developer and testing support, 58.0.3029.0`  seems to be a stable build which supports the issue.

I am not sure what the best fix for this is, I've documented which chrome version works in 69c24d9fba630827090483fd3b01ac8074fb5579 but that doesn't really fix the issue. 

* We could allow the user to specify which browsers they wish to run the integration tests on with something like `--env phantomjs,chrome,firefox`
* We could also just continue to throw an error since integration tests lose value when you start removing browsers from the test suite.
